version: '3.1'

services:
  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - 8080:80

  dbmysql:
    image: mysql
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: mydb 
